version: '3'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - /home/rocky/data/mongo_data:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:3001"
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
      - /home/rocky/data/uploads:/usr/src/app/uploads
      - /home/rocky/data/property_compressed:/usr/src/app/property_compressed

volumes:
  mongo_data:
