version: '3'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/rocky/data/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: appuser
      MONGO_INITDB_ROOT_PASSWORD: appsuer29292aakdnn23
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:3001"
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
      - /home/rocky/data/uploads:/usr/src/app/uploads

volumes:
  mongo_data:
