version: '3'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:3001"
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo_data:
